### ISSUE TITLE
Adding a way to remove the volume stream listener

### ISSUE THREAD

**Issue by PeperMarkreel** [JiangJuHong/FlutterPerfectVolumeControl#13]
Hi,

Simply adding 

  /// Remove listener streams
  static void removeListener(){
    _channel.setMethodCallHandler(null);
  }

to perfect_volume_control.dart would provide users with the option to remove the listener. 

When I do not remove the listener, it still fires when my app is in a different screen. Calling this when I push for a new screen, solves it. Thanks for publishing this great package! :)

**Comment by JiangJuHong** [comment]
This is a good suggestion, but I'm thinking about whether, in business, you should just use steam.cancel to cancel events you don't want to listen to, because relatively speaking, setMethodCallHandler is more like a global listener, it always exists, if What do you want to use, will it be available directly, avoiding init or uninit related operations?

**Comment by PeperMarkreel** [comment]
Ah you mean for example: 

```
    StreamSubscription subscription = PerfectVolumeControl.stream.listen((volume) {
       volumeHasChanged();
    });

```
and in dispose
`subscription.cancel();`
    
That is a better solution indeed. First time working with streams for me (sorry to have opened an issue!).

**Comment by JiangJuHong** [comment]
I'm sure this question can be closed
